version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean build
      - echo Building the Docker image... `$REPOSITORY_URI`
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"cicd-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
      -
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
  base-directory: './build/libs'
reports:
  test-report-group: #Junit reports
    files:
      - 'TEST-boris.maths.MathsApplicationTests.xml'
    #discard-paths: false #do not remove file paths from test result files
    base-directory: './build/test-results/test'