spring:
  security:
    user:
      name: DEPREDEV
      password: 123CAIU
    oauth2:
      client:
        registration:
          github:
            client-id: 0f7fdd34c81c13afda9e
            client-secret: b47bc1c77f0c6c15bb5138be37effc04bb01a841
            scope:
              - user:email
              - read:user